### ISSUE TITLE
Guava-GWT 18 does not compile with Java8

### ISSUE THREAD

**Issue by confile** [google/guava#1939]
I used the following in my gwt.xml file: 

```
<inherits name="com.google.common.collect.Collect"/>
```
and I included both guava18 and guava-gwt18 on my classpath. the compiler error was: 

```
   Tracing compile failure path for type 'com.google.common.collect.Collections2'
      [ERROR] Errors in 'com/google/common/collect/Collections2.java'
         [ERROR] Line 201: The method and(Predicate<capture#14-of ? super E>, Predicate<capture#15-of ?>) is undefined for the type Collections2.FilteredCollection<E>
         [ERROR] Line 206: The method and(Predicate<capture#16-of ? super E>, Predicate<capture#17-of ?>) is undefined for the type Collections2.FilteredCollection<E>
   Tracing compile failure path for type 'com.google.common.collect.Maps'
      [ERROR] Errors in 'com/google/common/collect/super/com/google/common/collect/Maps.java'
         [ERROR] Line 2244: The method and(Predicate<capture#263-of ? super Map.Entry<K,V>>, Predicate<capture#264-of ? super Map.Entry<K,V>>) is undefined for the type Predicates
         [ERROR] Line 2343: The method and(Predicate<capture#265-of ? super Map.Entry<K,V>>, Predicate<capture#266-of ? super Map.Entry<K,V>>) is undefined for the type Predicates
   Tracing compile failure path for type 'com.google.common.collect.Multimaps'
      [ERROR] Errors in 'com/google/common/collect/super/com/google/common/collect/Multimaps.java'
         [ERROR] Line 1691: The method and(Predicate<capture#83-of ? super K>, Predicate<capture#84-of ? super K>) is undefined for the type Predicates
         [ERROR] Line 1954: The method and(Predicate<capture#105-of ? super Map.Entry<K,V>>, Predicate<capture#106-of ? super Map.Entry<K,V>>) is undefined for the type Predicates
         [ERROR] Line 1735: The method and(Predicate<capture#87-of ? super K>, Predicate<capture#88-of ? super K>) is undefined for the type Predicates
         [ERROR] Line 1779: The method and(Predicate<capture#91-of ? super K>, Predicate<capture#92-of ? super K>) is undefined for the type Predicates
         [ERROR] Line 1940: The method and(Predicate<capture#103-of ? super Map.Entry<K,V>>, Predicate<capture#104-of ? super Map.Entry<K,V>>) is undefined for the type Predicates
   [ERROR] Aborting compile due to errors in some input files
```

**Comment by cpovirk** [comment]
I put together a problem with Java 8, guava-gwt-18, GWT 2.7.0, and a client call to `Collections2.filter`, and it works in both SuperDevMode and Prod Mode. Can you give me some more detail about how to reproduce the problem (ideally a small example GWT project)?

**Comment by confile** [comment]
I created a sample project. You will find it here: https://github.com/confile/GuavaGWT-Java8-Test

**Comment by cpovirk** [comment]
Thanks! I am still being a bit clueless here -- a bit caught in my bubble of writing GWT applications only with our internal tools :( I've loaded the project into Eclipse to compile there. If I pass `-strict`, then it fails with the `BitSet` problem (issue 1824). If I omit `-strict`, then it compiles successfully. Any other hints for how to reproduce the `Collections`/`Maps`/`Multimaps` problem?

**Comment by confile** [comment]
I have no idea but you should keep the ``-strict``.

**Comment by cpovirk** [comment]
Are you able to reproduce this in the same project? And is the sample project using GWT 2.5.1?

I found the other discussion on http://stackoverflow.com/q/27870181/28465, which suggests that you're seeing this problem with the latest GWT snapshot rather than with 2.5.1. That may explain why I haven't been able to reproduce it. (I started looking into pulling files from, e.g., https://oss.sonatype.org/content/repositories/google-snapshots/com/google/gwt/gwt-servlet/2.8.0-SNAPSHOT/)

**Comment by confile** [comment]
Here is a demo project for this issue to be reproduced: https://github.com/confile/gwtGuavaTest2

I am using the latest GWT2.7SNAPSHOT with JAva8 Update15 on OSX.

**Comment by cpovirk** [comment]
Thanks. I'm able to reproduce with the GWT 2.8 snapshot and Java 8.

Since the GWT team has [an accepted bug](https://code.google.com/p/google-web-toolkit/issues/detail?id=9036) for this problem, and since [the underlying problem in the Eclipse compiler](https://bugs.eclipse.org/bugs/show_bug.cgi?id=443596) has been fixed, and since it occurs only at the GWT trunk, I don't think there's much for us to do here.

**Comment by confile** [comment]
Okay but still I cannot compile the current Guava-GWT project from source.

**Comment by cpovirk** [comment]
Oh, like in #1940, right? Sorry. I submitted a fix internally, but we haven't pushed it out yet. I'll do so now.

**Comment by confile** [comment]
Great thank you!

**Comment by confile** [comment]
Well now I can compile guava and guava-gwt from source but when using in a GWT project I still get the error.

**Comment by confile** [comment]
Here is a demo project for eclipse which reproduces this error: 

https://github.com/confile/GWTQueryJava8Test

**Comment by cpovirk** [comment]
It sounds like GWT has made the necessary upgrade on their end: https://code.google.com/p/google-web-toolkit/issues/detail?id=9036#c7

**Comment by confile** [comment]
Great

**Comment by cpovirk** [comment]
New GWT link: https://github.com/gwtproject/gwt/issues/8989
