### ISSUE TITLE
Remove jsr305 dependency

### ISSUE THREAD

**Issue by orionll** [google/guava#2782]
I tried to compile guava with Java 9 and failed. The problem is the jsr305 dependency. It contains a package `javax.annotation` which conflicts with the same package in the `java.base` module (`javax.annotation.PostConstruct` annotation and others). Java 9 forbids split packages.

Java 9 is not released yet, but we can already start thinking what to do. Is it possible to replace jsr305 annotations with similar annotations?

**Comment by jbduncan** [comment]
Related issue: https://github.com/google/guava/issues/2571

**Comment by ben-manes** [comment]
I thought this was resolved as part of [JEP 261](http://openjdk.java.net/jeps/261#EE-modules)

**Comment by orionll** [comment]
@ben-manes is right. The problem has nothing to do with split packages because `java.se` does not include the `javax.xml.ws.annotation` module and there is no conflict during compilation. However, there is still an issue with the `jsr305` module name. This is an automatic module (since it does not have module-info.java) and I don't know what to write in module-info.java. This does not work:

```java
module java {
    requires jsr305; // javac fails: module not found: jsr305
}
```
I think the problem is the Java 9 module naming rules. It discourages modules with terminal digits. And if I change the jar name to jsr.jar, everything gets fine:

```java
module java {
    requires jsr; // OK
}
```

So, renaming jsr305.jar to jsr.jar can be a workaround.

**Comment by orionll** [comment]
I think this can be closed since Java 9 now allows digits at the end of module names: http://openjdk.java.net/projects/jigsaw/spec/issues/#VersionsInModuleNames
